<a href="https://colab.research.google.com/github/testgithubritkaif/numpy/blob/main/Copy_of_task_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [ ]:
# code here
#  Sort this matrix. np.sort()
import numpy as np
arr = np.random.randint(0,100,(4,3))
print(np.sort(arr))
# ii. Sort this matrix based on values in 2nd column.
print()
print(arr[arr[:,2].argsort()])

print()
# iii. Sort this matrix based on max value in each row.
print(arr[arr.max(axis=1).argsort()])

print()

# iv. Sort based on elements value.
print(np.sort(arr.flatten()).reshape(arr.shape))



[[15 22 77]
 [19 21 77]
 [60 74 91]
 [53 91 92]]

[[77 21 19]
 [15 77 22]
 [74 60 91]
 [53 92 91]]

[[15 77 22]
 [77 21 19]
 [74 60 91]
 [53 92 91]]

[[15 19 21]
 [22 53 60]
 [74 77 77]
 [91 91 92]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [ ]:
# code here
marks = np.array( [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
marks
# i. Add marks every student of an extra subject in the same array.
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(5,1)
marks =  np.hstack((marks,extra_subject))
print(marks)
print()


# ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1,5)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1,5)
marks = np.vstack((rec1,marks,rec2))
print(marks)

print()

# iii. Add extra column with sum of all subjects(5-subjects) marks
sum_col = marks.sum(axis=1).reshape(7,1)
marks =(np.hstack((marks,sum_col)))
print(marks)
print()

# iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows
total_marks = marks[marks[:,-1].argsort()[::-1]]
print(total_marks[:2])





[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]

[[77 83 98 95 89]
 [13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [92 71 52 61 53]]

[[ 77  83  98  95  89 442]
 [ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 92  71  52  61  53 329]]

[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [ ]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
print(f"THis is rose wise unique{np.unique(arr,axis=0)}")
print(f"THis is column wise unique{np.unique(arr,axis=1)}")

THis is rose wise unique[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
THis is column wise unique[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [ ]:
# code here
print(np.flip(arr))

[[1 1 3 3 2 1]
 [8 8 8 3 2 1]
 [8 8 2 1 9 0]
 [1 1 3 3 2 1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [ ]:
# code here
arr = np.array([[1,2,3,4,5],
       [10,-3,30,4,5],
       [3,2,5,-4,5],
       [9,7,3,6,5]])
x = 6
print(np.where(arr>x))

(array([1, 1, 3, 3]), array([0, 2, 0, 1]))


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [ ]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [ ]:
# code here
print(np.concatenate((arr1,arr2,arr3)))

[0 1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [3]:
# code here
import numpy as np
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
max_arr = np.max(arr)
print(max_arr)
min_arr = np.min(arr)
print(min_arr)
arr = arr[0][np.logical_and(arr[0]!=max_arr, arr[0]!=min_arr)].reshape(1,-1)
print(arr)



998
103
[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 627 920 824 356 825 173
  323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211 771
  270 308 231 952 514 699 702 433 900 373 318 265 503 320 230 324 922 967
  620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930 325 729
  426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528 395 525
  922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859 618 226
  695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748 291 194
  761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207 883 588]]


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [ ]:
# code here
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
arr[(arr < 100)] = 100
arr[(arr > 200)] = 20
print(np.cumsum(np.sort(arr)))

[  103   220   343   479   616   787   960  1138  1319  1510  1703  1897
  2094  2294  2494  2694  2894  3094  3294  3494  3694  3894  4094  4294
  4494  4694  4894  5094  5294  5494  5694  5894  6094  6294  6494  6694
  6894  7094  7294  7494  7694  7894  8094  8294  8494  8694  8894  9094
  9294  9494  9694  9894 10094 10294 10494 10694 10894 11094 11294 11494
 11694 11894 12094 12294 12494 12694 12894 13094 13294 13494 13694 13894
 14094 14294 14494 14694 14894 15094 15294 15494 15694 15894 16094 16294
 16494 16694 16894 17094 17294 17494 17694 17894 18094 18294 18494 18694
 18894 19094 19294 19494 19694 19894 20094 20294 20494 20694 20894 21094
 21294 21494 21694 21894 22094 22294 22494 22694 22894 23094 23294 23494
 23694 23894 24094 24294 24494 24694 24894 25094 25294 25494 25694 25894
 26094 26294 26494 26694 26894 27094 27294 27494 27694 27894 28094 28294
 28494 28694 28894 29094 29294 29494 29694 29894 30094 30294 30494 30694
 30894 31094 31294 31494 31694 31894 32094 32294 32

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [5]:
# code here
np.random.seed(400)
arr = np.random.rand(200).reshape((1, 200))
arr = np.round(arr,3)
print(np.percentile(arr,0))
print(np.percentile(arr,1))


0.001
0.01299
