<a href="https://colab.research.google.com/github/testgithubritkaif/numpy/blob/main/Task_13_NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
Null_vector = np.zeros(10)
Null_vector[4]=1
Null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
null_vector = np.eye(1, 10, k=6, dtype=float)[0]

print(null_vector)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
identity_matrix = np.eye(3)
print("3x3 Identity Matrix (using np.eye):")
print(identity_matrix)

3x3 Identity Matrix (using np.eye):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Code here
b = int(input("enter the num 1 :"))
c = int(input("enter the num 2 :"))
random_array =np.random.randint(1,100, size=(b,c))
print(f" the random_array is {random_array}")
print((f"random_array avg is {np.mean(random_array)}"))

enter the num 1 :2
enter the num 2 :6
 the random_array is [[16 78 95 70 67 98]
 [ 8 75 59 38 90 66]]
random_array avg is 63.333333333333336


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
def parameter_function(a,b):
  array = np.ones((a,b))
  array[1:3,1:3]=0
  # array[1:-1,1:-1]=0
  return array
parameter_function(4,4)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
d =np.linspace(0,1,10)
d

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
# NO because the shap is different
identity_matrix = np.identity(3,4)
identity_matrix
#we can use this np.eye() function
# identity_matrix = np.eye(3,4)
# identity_matrix


TypeError: Cannot interpret '4' as a data type

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
matr =np.tile( np.arange(5),(5,1))
matr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
random_point = np.random.randint(1,100 , size=(10,2))
coordinates_point = np.array([2,3])
distance = np.sqrt(((random_point - coordinates_point) ** 2).sum(axis=1))
distance = distance.astype(int)
print(f"The random_point is {random_point}")
print(f"The distance is {distance}")


The random_point is [[29 27]
 [23 33]
 [14 21]
 [15 72]
 [38 89]
 [97 22]
 [53 13]
 [72 48]
 [34 26]
 [87 59]]
The distance is [ 36  36  21  70  93  96  51  83  39 101]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
shape = (6, 7, 8)

# Find the index of the 100th element (0-based index 99)
index = np.unravel_index(99, shape)

print(index)

(np.int64(1), np.int64(5), np.int64(3))


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
l = input("enter the num 1 :").split()
l1=np.array(l,dtype=float)
print(l1[::-1])

enter the num 1 :0 2 -2 0 2
[ 2.  0. -2.  2.  0.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
array1=np.array([],dtype=int)
array_count = array1.size
print(f"elements_count : {array_count}")
array2=np.array([1, 2],)
array_count2 = array2.size
print(f"elements_count : {array_count2}")

elements_count : 0
elements_count : 2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
# def Softmax_function(z):
#   e_z = np.exp(z - np.max(z))
#   softmax_result = e_z / np.sum(e_z)
#   return softmax_result
#   z =np.array[86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852, 37.20006318]
#   output = Softmax_function(z)
#   print(output)

import numpy as np

def softmax(x):
    """
    Compute the softmax of a numpy 1D array.

    Parameters:
    x (numpy.ndarray): A 1D numpy array

    Returns:
    numpy.ndarray: Softmax of the input array

    Raises:
    TypeError: If input is not a numpy 1D array
    """
    if not isinstance(x, np.ndarray) or x.ndim != 1:
        raise TypeError("Input must be a numpy 1D array")

    # Subtract the max for numerical stability
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

# Example usage:
input_array = np.array([86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318])
output = softmax(input_array)
print(output)



[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

###`Q-14:` Subtract the mean of each row from a matrix.

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
import numpy as np
arr = np.random.randint(1,100,25).reshape(5,5)
print(arr)
print("and ")
arr[:,[0,1]] = arr[:,[1,0]]
print(arr)

[[97 23 20 14 98]
 [16 71 27 23 25]
 [27 77 77 58 42]
 [81 92 66 27 65]
 [58 33 69 40 65]]
and 
[[23 97 20 14 98]
 [71 16 27 23 25]
 [77 27 77 58 42]
 [92 81 66 27 65]
 [33 58 69 40 65]]


###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here

In [ ]:
import numpy as np
arr = np.random.randint(1,100,25)
print(arr)
arr[arr % 2==1]= -1
arr

[59 14 96 42 54 17 38 89 28 50 87  5  7 74 43 25 94 51 65  1 98  1 64 41
  7]


array([-1, 14, 96, 42, 54, -1, 38, -1, 28, 50, -1, -1, -1, 74, -1, -1, 94,
       -1, -1, -1, 98, -1, 64, -1, -1])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
result = np.maximum(a,b)
result

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2939, 1694, 6680, 8865, 2684],
       [4066, 4573,  327, 6525,  851],
       [5997, 7481, 2315, 5863, 9615],
       [7821, 1225, 9138, 1114, 4885],
       [7715, 8046, 9105, 3935, 3182],
       [8842, 4836, 2705, 3751, 3800],
       [4132, 1400, 7844, 9471, 7526],
       [2749, 2624, 6900, 1576, 7515]])

In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
a = np.array([1,2,3])
# result =([np.repeat(a,3),np.tile(a,3)])
result = np.concatenate([np.repeat(a, 3), np.tile(a, 3)])
print(result)


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
